builders:
  freezed:
    target: ":freezed"
    import: "package:freezed/builder.dart"
    builder_factories:
      - "freezed"
    build_extensions:
      ".dart":
        - ".freezed.dart"
        - ".g.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "pubspec.yaml"
  json_serializable:
    target: ":json_serializable"
    import: "package:json_serializable/builder.dart"
    builder_factories:
      - "jsonSerializable"
    build_extensions:
      ".dart":
        - ".g.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "pubspec.yaml"
  riverpod_generator:
    target: ":riverpod_generator"
    import: "package:riverpod_generator/builder.dart"
    builder_factories:
      - "riverpodGenerator"
    build_extensions:
      ".dart":
        - ".g.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "pubspec.yaml"
  drift_dev:
    target: ":drift_dev"
    import: "package:drift_dev/builder.dart"
    builder_factories:
      - "driftDev"
    build_extensions:
      ".dart":
        - ".g.dart"
        - ".drift.dart"
    auto_apply: dependents
    build_to: source
    required_inputs:
      - "pubspec.yaml"

targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          freezed:
            # Add any freezed options here
      json_serializable:
        enabled: true
        options:
          json_serializable:
            any_map: true
            checked: true
            create_factory: true
            create_to_json: true
            explicit_to_json: true
            field_rename: none
            include_if_null: false
      riverpod_generator:
        enabled: true
      drift_dev:
        enabled: true
        options:
          drift_dev:
            generate_getters: true
            generate_setters: true
            generate_create_table: true
            generate_insert: true
            generate_update: true
            generate_delete: true
            generate_selectable: true
            generate_companion: true
            generate_data_class: true
            generate_copy_with: true
            generate_equality: true
            generate_hash_code: true
            generate_to_string: true

  $package$:
    sources:
      - lib/**
    builders:
      freezed:
        generate_for:
          - lib/shared/models/track.dart
      json_serializable:
        generate_for:
          - lib/shared/models/track.dart
      riverpod_generator:
        generate_for:
          - lib/core/presentation/providers.dart
      drift_dev:
        generate_for:
          - lib/core/data/database.dart