#!/bin/bash
# Local Build Script for YTMusic Client
# Builds debug/release APKs and AABs with proper versioning and signing

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
BUILD_TYPE="both"
VERSION_NAME=""
VERSION_CODE=""
CLEAN=false
INSTALL=false
DEVICE_ID=""

# Help function
show_help() {
    cat << EOF
Usage: $0 [OPTIONS]

Build YTMusic Android app locally with proper signing.

OPTIONS:
    -t, --type TYPE         Build type: debug, release, both (default: both)
    -v, --version VERSION   Version name (e.g., 1.0.0). Auto-detected from git tag if not provided.
    -c, --code CODE         Version code (integer). Auto-calculated from version name if not provided.
    --clean                 Clean build directory before building
    -i, --install           Install APK to connected device after build
    -d, --device DEVICE_ID  Target device ID for installation
    -h, --help              Show this help message

EXAMPLES:
    $0                              # Build both debug and release
    $0 -t release                   # Build only release
    $0 -t debug -i                  # Build debug and install to device
    $0 -v 1.0.0 -c 10000 --clean    # Clean build with specific version
    $0 -t release -v 2.0.0-beta.1   # Build release with pre-release version

ENVIRONMENT VARIABLES (for signing):
    ANDROID_DEBUG_KEYSTORE_PATH     Path to debug.keystore (default: android/app/debug.keystore)
    ANDROID_DEBUG_STORE_PASSWORD    Debug keystore password
    ANDROID_DEBUG_KEY_ALIAS         Debug key alias
    ANDROID_DEBUG_KEY_PASSWORD      Debug key password
    ANDROID_RELEASE_KEYSTORE_PATH   Path to release.keystore
    ANDROID_RELEASE_STORE_PASSWORD  Release keystore password
    ANDROID_RELEASE_KEY_ALIAS       Release key alias
    ANDROID_RELEASE_KEY_PASSWORD    Release key password

EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--type)
            BUILD_TYPE="$2"
            shift 2
            ;;
        -v|--version)
            VERSION_NAME="$2"
            shift 2
            ;;
        -c|--code)
            VERSION_CODE="$2"
            shift 2
            ;;
        --clean)
            CLEAN=true
            shift
            ;;
        -i|--install)
            INSTALL=true
            shift
            ;;
        -d|--device)
            DEVICE_ID="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# Validate build type
if [[ ! "$BUILD_TYPE" =~ ^(debug|release|both)$ ]]; then
    echo -e "${RED}Invalid build type: $BUILD_TYPE. Must be debug, release, or both.${NC}"
    exit 1
fi

# Auto-detect version from git tag if not provided
if [ -z "$VERSION_NAME" ]; then
    VERSION_NAME=$(git describe --tags --always --dirty 2>/dev/null | sed 's/^v//')
    if [ -z "$VERSION_NAME" ]; then
        VERSION_NAME="1.0.0-dev"
    fi
    echo -e "${BLUE}Auto-detected version: $VERSION_NAME${NC}"
fi

# Auto-calculate version code if not provided
if [ -z "$VERSION_CODE" ]; then
    # Extract major.minor.patch from version (ignore pre-release suffix)
    CLEAN_VERSION=$(echo "$VERSION_NAME" | sed 's/-.*//')
    IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_VERSION"
    MAJOR=${MAJOR:-0}
    MINOR=${MINOR:-0}
    PATCH=${PATCH:-0}
    VERSION_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))
    echo -e "${BLUE}Auto-calculated version code: $VERSION_CODE${NC}"
fi

# Validate version code
if ! [[ "$VERSION_CODE" =~ ^[0-9]+$ ]]; then
    echo -e "${RED}Version code must be an integer${NC}"
    exit 1
fi

# Check Flutter
if ! command -v flutter &> /dev/null; then
    echo -e "${RED}Flutter not found in PATH${NC}"
    exit 1
fi

FLUTTER_VERSION=$(flutter --version | head -1)
echo -e "${BLUE}Using Flutter: $FLUTTER_VERSION${NC}"

# Setup keystore.properties
echo -e "${YELLOW}Configuring signing...${NC}"
cat > android/keystore.properties << EOF
# Auto-generated by build.sh - DO NOT COMMIT
debug.storeFile=${ANDROID_DEBUG_KEYSTORE_PATH:-../app/debug.keystore}
debug.storePassword=${ANDROID_DEBUG_STORE_PASSWORD:-android}
debug.keyAlias=${ANDROID_DEBUG_KEY_ALIAS:-debug}
debug.keyPassword=${ANDROID_DEBUG_KEY_PASSWORD:-android}

release.storeFile=${ANDROID_RELEASE_KEYSTORE_PATH:-../app/release.keystore}
release.storePassword=${ANDROID_RELEASE_STORE_PASSWORD}
release.keyAlias=${ANDROID_RELEASE_KEY_ALIAS}
release.keyPassword=${ANDROID_RELEASE_KEY_PASSWORD}
EOF

# Check debug keystore
if [[ "$BUILD_TYPE" == "debug" || "$BUILD_TYPE" == "both" ]]; then
    DEBUG_KEYSTORE="${ANDROID_DEBUG_KEYSTORE_PATH:-android/app/debug.keystore}"
    if [ ! -f "$DEBUG_KEYSTORE" ]; then
        echo -e "${YELLOW}Debug keystore not found at $DEBUG_KEYSTORE${NC}"
        echo -e "${YELLOW}Generating new debug keystore...${NC}"
        mkdir -p "$(dirname "$DEBUG_KEYSTORE")"
        keytool -genkeypair \
            -alias debug \
            -keypass android \
            -keystore "$DEBUG_KEYSTORE" \
            -storepass android \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000
        echo -e "${GREEN}Debug keystore generated${NC}"
    fi
fi

# Check release keystore
if [[ "$BUILD_TYPE" == "release" || "$BUILD_TYPE" == "both" ]]; then
    RELEASE_KEYSTORE="${ANDROID_RELEASE_KEYSTORE_PATH:-android/app/release.keystore}"
    if [ ! -f "$RELEASE_KEYSTORE" ]; then
        echo -e "${RED}Release keystore not found at $RELEASE_KEYSTORE${NC}"
        echo -e "${YELLOW}Set ANDROID_RELEASE_KEYSTORE_PATH or place release.keystore in android/app/${NC}"
        if [[ "$BUILD_TYPE" == "release" ]]; then
            exit 1
        else
            echo -e "${YELLOW}Skipping release build${NC}"
            BUILD_TYPE="debug"
        fi
    elif [ -z "$ANDROID_RELEASE_STORE_PASSWORD" ] || [ -z "$ANDROID_RELEASE_KEY_ALIAS" ] || [ -z "$ANDROID_RELEASE_KEY_PASSWORD" ]; then
        echo -e "${RED}Release keystore credentials not set in environment${NC}"
        if [[ "$BUILD_TYPE" == "release" ]]; then
            exit 1
        else
            echo -e "${YELLOW}Skipping release build${NC}"
            BUILD_TYPE="debug"
        fi
    fi
fi

# Clean if requested
if [ "$CLEAN" = true ]; then
    echo -e "${YELLOW}Cleaning build directories...${NC}"
    flutter clean
    rm -rf build/
    rm -rf android/app/build/
fi

# Get dependencies
echo -e "${YELLOW}Getting dependencies...${NC}"
flutter pub get

# Generate code
echo -e "${YELLOW}Generating code...${NC}"
flutter pub run build_runner build --delete-conflicting-outputs

# Build function
build_flutter() {
    local type=$1
    local target=$2
    local suffix=$3
    
    echo -e "${BLUE}Building $type for $target...${NC}"
    
    flutter build apk --$type \
        --target-platform $target \
        --split-per-abi \
        --build-name=$VERSION_NAME \
        --build-number=$VERSION_CODE
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ $type ($target) APK built successfully${NC}"
    else
        echo -e "${RED}✗ $type ($target) APK build failed${NC}"
        return 1
    fi
}

# Build APKs
ARCHS=("arm64-v8a:arm64" "armeabi-v7a:arm" "x86_64:x64")
FAILED=()

for arch_pair in "${ARCHS[@]}"; do
    IFS=':' read -r arch flutter_target <<< "$arch_pair"
    
    if [[ "$BUILD_TYPE" == "debug" || "$BUILD_TYPE" == "both" ]]; then
        build_flutter "debug" "$flutter_target" "$arch" || FAILED+=("debug-$arch")
    fi
    
    if [[ "$BUILD_TYPE" == "release" || "$BUILD_TYPE" == "both" ]]; then
        build_flutter "release" "$flutter_target" "$arch" || FAILED+=("release-$arch")
    fi
done

# Build App Bundles
if [[ "$BUILD_TYPE" == "debug" || "$BUILD_TYPE" == "both" ]]; then
    echo -e "${BLUE}Building debug App Bundle...${NC}"
    flutter build appbundle --debug \
        --build-name=$VERSION_NAME \
        --build-number=$VERSION_CODE || FAILED+=("debug-aab")
fi

if [[ "$BUILD_TYPE" == "release" || "$BUILD_TYPE" == "both" ]]; then
    echo -e "${BLUE}Building release App Bundle...${NC}"
    flutter build appbundle --release \
        --build-name=$VERSION_NAME \
        --build-number=$VERSION_CODE || FAILED+=("release-aab")
fi

# Organize artifacts
echo -e "${YELLOW}Organizing artifacts...${NC}"
mkdir -p artifacts

for arch_pair in "${ARCHS[@]}"; do
    IFS=':' read -r arch flutter_target <<< "$arch_pair"
    
    if [[ "$BUILD_TYPE" == "debug" || "$BUILD_TYPE" == "both" ]]; then
        SRC="build/app/outputs/flutter-apk/app-${flutter_target}-debug.apk"
        if [ -f "$SRC" ]; then
            cp "$SRC" "artifacts/ytmusic-${VERSION_NAME}-${arch}-debug.apk"
        fi
    fi
    
    if [[ "$BUILD_TYPE" == "release" || "$BUILD_TYPE" == "both" ]]; then
        SRC="build/app/outputs/flutter-apk/app-${flutter_target}-release.apk"
        if [ -f "$SRC" ]; then
            cp "$SRC" "artifacts/ytmusic-${VERSION_NAME}-${arch}-release.apk"
        fi
    fi
done

# Copy AABs
if [[ "$BUILD_TYPE" == "debug" || "$BUILD_TYPE" == "both" ]]; then
    if [ -f "build/app/outputs/bundle/debug/app-debug.aab" ]; then
        cp "build/app/outputs/bundle/debug/app-debug.aab" "artifacts/ytmusic-${VERSION_NAME}-debug.aab"
    fi
fi

if [[ "$BUILD_TYPE" == "release" || "$BUILD_TYPE" == "both" ]]; then
    if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
        cp "build/app/outputs/bundle/release/app-release.aab" "artifacts/ytmusic-${VERSION_NAME}-release.aab"
    fi
fi

# Verify signatures
echo -e "${YELLOW}Verifying signatures...${NC}"
for f in artifacts/*.apk; do
    if [ -f "$f" ]; then
        echo -e "${BLUE}Verifying: $(basename "$f")${NC}"
        jarsigner -verify -verbose -certs "$f" 2>&1 | grep -E "(verified|X.509|CN=)" | head -5
    fi
done

# Summary
echo ""
echo -e "${GREEN}=== BUILD SUMMARY ===${NC}"
echo -e "Version: ${BLUE}$VERSION_NAME${NC} (code: ${BLUE}$VERSION_CODE${NC})"
echo -e "Build type: ${BLUE}$BUILD_TYPE${NC}"
echo -e "Artifacts in: ${BLUE}artifacts/${NC}"
ls -la artifacts/

if [ ${#FAILED[@]} -gt 0 ]; then
    echo -e "${RED}Failed builds: ${FAILED[*]}${NC}"
    exit 1
else
    echo -e "${GREEN}All builds successful!${NC}"
fi

# Install if requested
if [ "$INSTALL" = true ]; then
    if ! command -v adb &> /dev/null; then
        echo -e "${RED}adb not found in PATH${NC}"
        exit 1
    fi
    
    # Determine which APK to install
    APK_FILE=""
    if [[ "$BUILD_TYPE" == "debug" || "$BUILD_TYPE" == "both" ]]; then
        APK_FILE=$(ls artifacts/*-arm64-v8a-debug.apk 2>/dev/null | head -1)
    fi
    if [ -z "$APK_FILE" ] && [[ "$BUILD_TYPE" == "release" || "$BUILD_TYPE" == "both" ]]; then
        APK_FILE=$(ls artifacts/*-arm64-v8a-release.apk 2>/dev/null | head -1)
    fi
    
    if [ -z "$APK_FILE" ]; then
        echo -e "${RED}No suitable APK found for installation${NC}"
        exit 1
    fi
    
    ADB_CMD="adb"
    if [ -n "$DEVICE_ID" ]; then
        ADB_CMD="adb -s $DEVICE_ID"
    fi
    
    echo -e "${YELLOW}Installing $APK_FILE...${NC}"
    $ADB_CMD install -r "$APK_FILE"
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Installation successful!${NC}"
    else
        echo -e "${RED}Installation failed${NC}"
        exit 1
    fi
fi